name: Build Pesto Windows App
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Nativefier
        run: npm install -g nativefier

      - name: Run Build
        shell: bash
        run: |
          # --internal-urls ".*?" forces EVERY link to stay inside the app
          # Make sure icon.png and toolbar.js are in your main folder
          nativefier "https://github.io" \
          --name "PestoHome" \
          --platform "windows" \
          --icon "./icon.png" \
          --internal-urls ".*?" \
          --inject "./toolbar.js" \
          --overwrite \
          ./output_app/

      - name: Verify Output
        run: dir output_app

      - name: Save App as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PestoHome-Desktop-App
          path: output_app/
